todo_system/urls.py
from django.contrib import admin
from django.urls import path

from user_app.views import *
from task_app.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/',Register.as_view(),name='signup'),
    path('login/',LoginView.as_view(), name='login'),
    path('logout/',Logoutview.as_view(), name='logout'),
    path('task_add/',Add_task.as_view(), name='add_task'),
    path('',Tasklist.as_view(), name='home'),
    path('update_task/<int:pk>',TaskUpdate.as_view(), name='update_task'),
    path('delete_task/<int:pk>', Task_delete.as_view(), name= 'delete_task'),
    path('complete/<int:pk>', Task_complet.as_view(), name= "complete"),
    path('search/',TaskSearchView.as_view(),  name='search')

]

task_app/models.py
from django.db import models

# Create your models here.


from user_app.models import User

class TaskManager(models.Model):

    priority_choice = [('low','low'),
                       ('high','high'),
                       ]

    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    priority= models.CharField(max_length=30, choices=priority_choice)
    completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True,)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

user_app/models.py
from django.db import models

from django.contrib.auth.models import User



# Create your models here.

task_app/forms.py
from django import forms

from task_app.models import TaskManager

class Taskform(forms.ModelForm):

    class Meta:

        model = TaskManager

        fields =['title', 'description','priority' ]

user_app/forms.py
from django import forms

from user_app.models import User


class Userregister(forms.ModelForm):

    class Meta:

        model = User

        fields = ['username', 'email', 'password']

task_app/views.py
from django.shortcuts import render , redirect, get_object_or_404

from django.views.generic import View , UpdateView

from task_app.forms import Taskform

from task_app.models import TaskManager

from django.urls import reverse_lazy

from django.db.models import Q

# Create your views here.

class Add_task(View):

    def get(self,request):

        form=Taskform

        return render(request,'add_task.html',{'form':form})
    
    def post(self,request):

        form=Taskform(request.POST)

        if form.is_valid():

            print(form.cleaned_data)

            task=form.save(commit=False)

            task.user = request.user

            task.save()


        return redirect('home')
    


class Tasklist(View):

    def get (self, request):

        if request.user.is_authenticated:

            task = TaskManager.objects.filter(user=request.user)

            return render(request,'base.html', {'task':task})
        
        return render(request,'base.html')
    
    


class TaskUpdate(UpdateView):

    model = TaskManager

    form_class= Taskform

    template_name = 'update.html'

    success_url = reverse_lazy ('home')


    def get_queryset(self):
        return TaskManager.objects.filter(user=self.request.user)



class Task_delete(View):

    def get( self,request,**kwarges):

        id= kwarges.get('pk')

        task= get_object_or_404(TaskManager, id=id, user=request.user )

        task.delete()

        return redirect('home')
    


class Task_complet(View):

    def get(self, request,**kwargs):

        id= kwargs.get('pk')

        task=get_object_or_404(TaskManager, id=id , user=request.user)

        task.completed = True

        task.save()

        return redirect('home')




class TaskSearchView(View):

    template_name='task_search.html'

    def get(self,request):

        query= request.GET.get('q')

        # filtering all expenses of the logined user

        task= TaskManager.objects.filter(user=request.user)

        # filtering using the given query from thw filtered expence above

        if query:

            task = task.filter(Q(title__icontains = query) | Q(priority__icontains = query))



        return render(request, self.template_name,{'task':task})

user_app/views.py
from django.shortcuts import render ,redirect

from django.views.generic import View

from user_app.forms import Userregister

from user_app.models import User

from django.contrib.auth import authenticate , login, logout

# Create your views here.

class Register(View):

    def get (self,request):

        form=Userregister()

        return render(request,'register.html',{'form':form})
    

    def post(self,request):

        username=request.POST.get('username')

        email=request.POST.get('email')

        password=request.POST.get('password')


        User.objects.create_user(username=username,
                                 email=email,
                                 password=password)


        form=Userregister()

        return redirect('home')
    



class LoginView(View):

    def get(self, request):

        return render (request,'login.html')


    def post(self,request):

        username=request.POST.get('username')

        password=request.POST.get('password')


        user=authenticate(request,username=username, password=password)


        if user:

            login(request,user)


            return redirect('home')
        
        form=Userregister()
        
        return render(request,'register.html',{'form':form} )
    


class Logoutview(View):

    def get (self, request):

        logout(request)

        return redirect('home')

task_app/templates/add_task.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TODO | Add Task</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

</head>
<style>
    .add-form-container {
        max-width: 600px;
        margin: 20px auto;
        padding: 20px;
        background-color: #f8f9fa;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .form-group {
        margin-bottom: 15px;
    }

    .form-group .task-complete-area {
        display: flex;
        gap: 15px;
    }

    .form-group label {
        display: block;
        margin-bottom: 5px;
        font-weight: bold;
        color: #333;
    }

    .form-group input,
    .form-group textarea,
    .form-group select{
        width: 100%;
        padding: 10px;
        border: 1px solid #ced4da;
        border-radius: 5px;
        box-sizing: border-box;
    }

    

    .form-group textarea {
        height: 100px;
        resize: none;
    }

    .custom-checkbox {

        display: inline-block;
        width: 22px;
        height: 22px;
    }

    .form-actions {
    display: flex;
    justify-content: space-between;
    align-items: center;
    
}
</style>

<body style="width: 100vw; height: 100vh; display: flex; justify-content: center; align-items: center;">
    <div class="add-form-container w-100">
        <h1 class="text-center">Create Task</h1>

        <form action="" method="post">
            
            {% csrf_token %}

            <div class="form-group">
                <label for="id_task">Title:</label>
                {{form.title}}
            </div>

            <div class="form-group">
                <label for="id_description">Description:</label>
                {{form.description }}
            </div>

            <div class="form-group">
                <label for="priority">Priority:</label>
                {{form.priority }}

                
            </div>



            <!-- <div class="form-group">
                <div class="task-complete-area">
                    <label for="id_completed">Completed</label>
                    <label class="custom-checkbox">
                        {{ form.completed }}

                    </label>
                </div>
            </div> -->

            <div class="form-actions">
                <button type="submit" class="btn btn-primary w-25">Create</button>
                <a href="{% url 'home' %}" class="btn btn-secondary w-25">Cancel</a>
            </div>

        </form>

    </div>
</body>

</html>

task_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TODO APP | Home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <style>
        body {
            background-color: #f8f9fa;
            font-family: 'Poppins', sans-serif;
        }

        .card {
            border-radius: 15px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        }

        .balance-card {
            background: linear-gradient(135deg, #007bff, #00b4d8);
            color: white;
        }

        .income-card {
            border-left: 5px solid #28a745;
        }

        .expense-card {
            border-left: 5px solid #dc3545;
        }

        .table thead {
            background-color: #343a40;
            color: white;
        }

        .btn-add {
            background-color: #007bff;
            color: white;
            border-radius: 30px;
            padding: 10px 25px;
        }

        .btn-add:hover {
            background-color: #0056b3;
        }
    </style>
</head>

<body>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
        <div class="container">
            <a class="navbar-brand fw-bold" href="#"> TODO APP</a>
            <div class="ms-auto text-white">
                {% if request.user.is_authenticated %}
                <span>Welcome, {{ user.username }}</span>
                <a href="{% url 'logout' %}" class="btn btn-primary rounded-5 ms-5 ">Logout</a>
                {% else %}
                <a href="{% url 'login' %}" class="btn btn-primary">Login</a>

                {% endif %}

            </div>
        </div>
    </nav>

    <div class="container">

        {% if request.user.is_authenticated %}

        <!-- Add task Button -->
        <div class="d-flex justify-content-between align-items-center mb-3">
            <h4 class="fw-semibold">Recent Tasks</h4>
            <form action="{% url 'search' %}" method="get">

                <input type="search" name="q">
                <span><button type="submit">Search</button></span>
            </form>
            <a href="{% url 'add_task' %}" class="btn btn-add">
                + Add new
            </a>
        </div>

        <!-- task Table -->
        <div class="card">
            <div class="card-body">

                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Description</th>
                            <th>priority </th>
                            <th>Status</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for t in task %}
                        <tr>
                            <td>{{ t.title }}</td>
                            <td>{{ t.description }}</td>
                            <td>{{ t.priority }}</td>
                            <td>
                                {% if t.completed %}
                                <span class="badge bg-success">completed</span>
                                {% else %}
                                <span class="badge bg-danger">pending</span>
                                {% endif %}
                            </td>
                            <td>
                                <a href="{% url 'update_task' t.id %}" class="btn btn-sm btn-warning">Edit</a>
                                <a href="{% url 'delete_task' t.id %}" class="btn btn-sm btn-danger">Delete</a>
                                <a href="{% url 'complete' t.id %}" class="btn btn-sm "
                                    style="background-color: #00b4d8;">completed</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>


            </div>
        </div>
        {% else %}

        <!-- if not login -->

        <div class="text-center mt-5">
            <h3>Welcome to TODO</h3>
            <p class="text-muted">Please <a href="{% url 'login' %}">login</a> to view or add your tasks.</p>
        </div>
        {% endif %}


    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

task_app/templates/task_search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{task}}
</body>
</html>

task_app/templates/update.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TODO | Update Task</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

</head>
<style>
    .add-form-container {
        max-width: 600px;
        margin: 20px auto;
        padding: 20px;
        background-color: #f8f9fa;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .form-group {
        margin-bottom: 15px;
    }

    .form-group .task-complete-area {
        display: flex;
        gap: 15px;
    }

    .form-group label {
        display: block;
        margin-bottom: 5px;
        font-weight: bold;
        color: #333;
    }

    .form-group input,
    .form-group textarea,
    .form-group select{
        width: 100%;
        padding: 10px;
        border: 1px solid #ced4da;
        border-radius: 5px;
        box-sizing: border-box;
    }

    

    .form-group textarea {
        height: 100px;
        resize: none;
    }

    .custom-checkbox {

        display: inline-block;
        width: 22px;
        height: 22px;
    }

    .form-actions {
    display: flex;
    justify-content: space-between;
    align-items: center;
    
    

}
</style>

<body style="width: 100vw; height: 100vh; display: flex; justify-content: center; align-items: center;">
    <div class="add-form-container w-100">
        <h1 class="text-center">Update Task</h1>

        <form action="" method="post">
            
            {% csrf_token %}

            <div class="form-group">
                <label for="id_task">Title:</label>
                {{form.title}}
            </div>

            <div class="form-group">
                <label for="id_description">Description:</label>
                {{form.description }}
            </div>

            <div class="form-group">
                <label for="priority">Priority:</label>
                {{form.priority }}

                
            </div>



            <!-- <div class="form-group">
                <div class="task-complete-area">
                    <label for="id_completed">Completed</label>
                    <label  class="custom-checkbox bg-danger">
                        {{ form.completed }}
                        

                    </label>
                </div>
            </div> -->

            <div class="form-actions">
                <button type="submit" class="btn btn-primary w-25">Save</button>
                <a href="{% url 'home' %}" class="btn btn-secondary w-25">Cancel</a>
            </div>

        </form>

    </div>
</body>

</html>

user_app/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
        integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<style>
    .button {

        background-color: #94bbe9;
    }

    .button:hover {
        background-color: #EEAECA;
    }

    label {
        font-weight: 500;
        text-align: left;
    }
</style>

<body style="width: 100vw; height: 100vh; display: flex; justify-content: center; align-items: center;">
    <div class=" d-flex justify-content-center align-items-center shadow rounded  w-50">
        <div class=" p-4 w-50 ">
            <h2 class="text-center mb-4  "> SIGN IN</h2>
            <div class="d-flex justify-content-center align-items-center fs-2 " style="gap: 20px; ">
                <i class="fa-brands fa-instagram "></i>
                <i class="fa-brands fa-facebook"></i>
                <i class="fa-brands fa-google-plus"></i>
            </div>
            <p class="text-center mt-4 mb-3 fw-light">or use your email for registration</p>
            <hr>
            <form action=""  method="post">
                                {% csrf_token %}

                                <div>
                                    <label for="" >Username:
                                    </label>

                                    <input class="form-control mb-4 mt-3" type="text" name="username" id="username" placeholder="Enter your username" required>
                                </div>
                                <div class="d-flex align-items-center justify-content-between mb-3 ">
                                    <label class=" ">Password:</label>
                                    <div>
                                        <a style="color: #1b5cb8" class=" text-decoration-none " href="">Forgot
                                            password?</a>

                                    </div>

                                </div>
                                <input type="password" class="form-control  mb-3"name="password" id="password" placeholder="Enter your password" required>
                                <div class="text-dark">
                                    <input class="me-2" type="checkbox"> <label for="">Remember password</label>
                                </div>

                                <div class="d-flex justify-content-center align-items-center  mb-4 mt-4 ">
                                    <button type="submit" class="btn button rounded-5 w-50 "
                                        >
                                           Login
                                    </button>

                                </div>




                            </form>

        </div>

        <div class=" rounded-end  border-1 p-5 w-50   "
            style="background: #EEAECA;background: linear-gradient(282deg, rgba(238, 174, 202, 1) 0%, rgba(148, 187, 233, 1) 100%); height: 540px;">
            <h2 class="text-center  " style="margin-top: 100px;">Hello, Friend!</h2>
            <p class="text-center mt-5 fw-lighter text-body-secondary ">Enter your Personal details and start journey
                with us</p>
            <div class="d-flex justify-content-center align-items-center mb-5">
                <a href="{% url 'signup' %}" class="mb-5 btn btn-outline-primary text-dark W-50 ">REGISTER NOW</a>
            </div>
        </div>




    </div>

</body>

</html>

user_app/templates/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
        integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />


</head>
<style>
    .form-radiant {
            /* background: #ffffff; */
            /* padding: 40px 30px; */
            /* border-radius: 12px; */
            /* box-shadow: 0 8px 20px rgba(0, 0, 0, 0.1); */
            /* width: 400px; */
            text-align: center;
        }

        .form-radiant h1 {
            margin-bottom: 25px;
            color: #333;
        }

        .form-radiant label {
            display: block;
            text-align: left;
            margin-bottom: 5px;
            font-weight: 500;
            /* color: white; */
        }

        .form-radiant input {
            width: 100%;
            padding: 5px 12px;
            /* margin-bottom: 20px; */
            border: 1px solid #ccc;
            border-radius: 8px;
            font-size: 16px;
            transition: border-color 0.3s;
        }

        .form-radiant input:focus {
            border-color: #80deea;
            outline: none;
        }

        .button{
            
            background-color: #94bbe9 ;
        }

        .button:hover{
            background-color: #EEAECA;
        }
</style>

<body style="width: 100vw; height: 100vh; display: flex; justify-content: center; align-items: center;">
    <div class=" d-flex justify-content-center align-items-center shadow rounded " >
        <div class="rounded-start  border-1 p-5 w-50  " 
            style="background: #EEAECA;background: linear-gradient(282deg, rgba(238, 174, 202, 1) 0%, rgba(148, 187, 233, 1) 100%); height: 500px;">
            
            <h2 class="text-center mt-5 mb-5 ">Welcome Back</h2>
            <p class="text-center mt-5 mb-5 ">To keep connected with us please login with your personal info</p>
            <div class="d-flex justify-content-center align-items-center mb-5">
                <a href="{% url 'login' %}" type="submit" class="mb-5 btn btn-outline-primary text-dark w-50">SIGN IN</a>
            </div>
        </div>
        <div class=" p-4 w-50  mt-3 form-radiant ">
            <h2 class="text-center"> Create Account</h2>
            <div class="d-flex justify-content-center align-items-center  fs-2" style="gap: 20px;">
                <i class="fa-brands fa-instagram "></i>
                <i class="fa-brands fa-facebook"></i>
                <i class="fa-brands fa-google-plus"></i>
            </div>
            <p class="text-center fw-light mt-2">or use your email for registration</p>
            <hr>
            <form action="" method="post">

                {% csrf_token %}
                {{ form.as_p }}



                <div class="d-flex justify-content-center align-items-center mt-4">
                    <button class="btn button text-dark w-50  rounded-5">SIGN UP</button>
                </div>
        </div>

        </form>

    </div>

</body>

</html>